### ISSUE TITLE
SessionManager: self._session_index used but never assigned (typo for _session_workspace_index) → AttributeError writing runner identity every session (0.19.0rc1)

### ISSUE THREAD

**Issue by apanoia** [Jaato-framework-and-examples/jaato#1176]
## Summary

In `jaato-server 0.19.0rc1`, **every session** logs:

```
[WARNING] server.session_manager: runner identity not written to the workspace index
  for session <id> (AttributeError: 'SessionManager' object has no attribute '_session_index')
```

Root cause is a plain attribute-name mismatch: the index is created as `self._session_workspace_index`, but three call sites reference `self._session_index`, which is never assigned.

## Environment

- jaato-server 0.19.0rc1 (sdk 0.26.0rc1, Python 3.14). First observed right after upgrading from 0.18.0rc1.

## Root cause (all in `server/session_manager.py`)

- **Init:** `:1176` — `self._session_workspace_index = SessionWorkspaceIndex()`
- **Broken references (never-assigned name `self._session_index`):**
  - `:4714` — `self._session_index.record_identity(session_id, identity.to_dict())`
  - `:4779` — `self._session_index.record_identity(session.session_id, identity.to_dict())`
  - `:4812` — `stored = self._session_index.identity(session_id)`

The target class already has the methods, so this is a pure rename — `server/session_workspace_index.py`: `record_identity` at `:164`, `identity` at `:197` (alongside `record`/`resolve`/`forget`, which the correctly-named `self._session_workspace_index` uses elsewhere).

## Impact

- `:4714` / `:4779` are wrapped best-effort (WARNING/DEBUG), so they don't crash — but the **runner identity is silently never recorded** into `SessionWorkspaceIndex`, so its identity map stays empty. That degrades anything that reads identity back (e.g. WS/pinless-resume identity lookups).
- `:4812` (`identity()` read) is **not** wrapped in the surrounding block, so an identity-readback caller would hit an **uncaught** `AttributeError` rather than a `None`.

## Fix

Rename the three `self._session_index` → `self._session_workspace_index` (`:4714`, `:4779`, `:4812`).

## Test gap

No test asserts the identity round-trips through the index — a test that records a runner identity for a session and reads it back via `SessionWorkspaceIndex.identity()` would have caught the misnamed attribute (no kernel/AppArmor needed).

**Comment by apanoia** [comment]
Labelled `tech-debt` `P2`, matching #1056 — **this is the same defect**, filed seven days earlier from the code side with the note that it had no observed failure. This issue is that observation. Neither referenced the other, so the code analysis sat on one and the release reproduction on the other.

Two corrections to the report while linking them, both measured on `main` @ `de8cdb5a`.

## It is not a 0.19.0rc1 regression

`self._session_index` was introduced by `789e4abd` — the #812 commit itself, 2026-09-12 — and no commit has touched it since:

```
$ git tag --contains 789e4abd | grep jaato-server
jaato-server-0.14.0
jaato-server-0.15.0
jaato-server-0.16.0
jaato-server-0.17.0
jaato-server-0.18.0
```

So it ships in **every tagged release from 0.14.0 onward**, and 0.19.0rc1 is where it was noticed rather than where it started. Worth correcting because "regression" sends a reader bisecting, and there is nothing to bisect.

## The diagnosis is right, and the consequence is larger than the AttributeError

`SessionWorkspaceIndex` is constructed at `session_manager.py:1176` and bound to `self._session_workspace_index`; it carries `record_identity`, `identity` and `forget`. The three call sites reach for `self._session_index`, which has **no production assignment anywhere in the package**. A plain misspelling, as you say.

What that costs depends on the site, and only one of the three raises:

| site | guarded | today |
|---|---|---|
| `:4714` `record_identity` | `try/except Exception` | the write never lands; one **WARNING per session** |
| `:4779` `record_identity` | `try/except Exception` | the write never lands; **DEBUG**, silent in practice |
| `:4812` `identity` | **no** | raises — and it is reached only when the session is *not* in `_sessions`, which is the one case the index exists to answer |

So the visible `AttributeError` is the smaller half. The larger one is that **#812's third record has never been written, in any release**. Its own description is "the daemon-owned workspace index — the cross-workspace lookup for someone holding only an id"; the other two records (the live field and the session record) are reachable only from a daemon that already has the session, so the index is the half that motivated the feature. `CLAUDE.md` states the identity is "written to three places". It is written to two.

## Why P2 rather than higher

No session fails and no turn is lost: both writes are best-effort-wrapped, and the unguarded read is on an operator path. What is degraded is post-mortem and cross-workspace lookup — real, and the reason #812 exists, but it does not reach the band. Same calibration #1149 used ("does not reach P1, because nothing costs a turn"), and it matches #1056 so the pair filters together.

## The part neither issue says

Three test files mock the attribute into existence — `test_session_identity_and_bound_812.py`, `test_orphan_bound_observes_attachment_812.py`, and `test_unload_grace_1106.py` — and one asserts `record_identity.assert_called_once()` against a mock of an attribute the class does not have. `MagicMock` accepts any name, so configuring a symbol that exists and one that does not are indistinguishable at the call site.

#1056 counted **two** mocks a week ago; there are three. The third came in with #1106, which needed a `SessionManager` fixture and reasonably copied the one beside it. So the suite's confidence in this mechanism is *growing* while the mechanism does not exist — which is why the rename alone is not the whole fix, and why a guard that every attribute a test mocks onto a real production class actually exists on that class is worth more here than the three-character correction.

Suggested next step: close one of the two so the evidence lives in one place. No preference which; this one carries the release reproduction, #1056 carries the original code analysis.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by apanoia** [comment]
Fixed on `main` by `dc833450`, which reached it through **#1186**. Closing as completed.

It did not auto-close because of a merge-ordering gap worth recording: #1182 was merged at 12:14 with **one** commit (`c6430262`, the #1153 SDK floor). The second commit and the PR-body edit adding `Closes #1176` / `Closes #1056` both landed *after* that merge, so neither keyword was present when GitHub evaluated it, and #1186 then carried the commit without the keywords.

Verified on `origin/main` @ `e1648458`: zero reads of `self._session_index.` remain in `session_manager.py`, and `test_session_manager_reads_only_attributes_it_assigns.py` — the AST guard that every `self._x` read in `SessionManager` has an assignment in the class — is in the required `contract-guards` job.

---
_Generated by [Claude Code](https://claude.ai/code)_
